[package]
name = "hands_on_data_structures_algorithms-practice"
author = ["jisang <jsyun@email.com>"]
version = "0.1.0"
edition = "2021"
keywords = ["do", "not", "use"]
description = "Do not use this crate it is for demo purposes only"

[dependencies]
